[package]
name = "benchmark"
version = "1.0.0"
edition = "2024"

[dependencies]
framework.workspace = true

tracing.workspace = true
serde.workspace = true
chrono.workspace = true

[dev-dependencies]
criterion = "0"

[[bench]]
name = "json_bench"
harness = false
